name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI
    inputs:
      version:
        description: 'Version number (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Run tests
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Extract version from tag
      id: get_version
      run: |
        if [[ -n "${{ inputs.version }}" ]]; then
          # Manual trigger with version input
          VERSION="${{ inputs.version }}"
          VERSION="${VERSION#v}"  # Remove 'v' prefix if present
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
          # Tag trigger
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"  # Remove 'v' prefix
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          # Fallback
          echo "version=1.0.0" >> $GITHUB_OUTPUT
        fi

    - name: Pack
      run: dotnet pack src/TheFirstDescendant/TheFirstDescendant.csproj -c Release --no-build -o ./artifacts -p:PackageVersion=${{ steps.get_version.outputs.version }}

    - name: Publish to NuGet.org
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Publish to GitHub Packages
      run: |
        dotnet nuget update source github --username cmxl --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ./artifacts/*.nupkg
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ./artifacts/*.nupkg
